### ISSUE TITLE
How to use painter as a separte page ?

### ISSUE THREAD

**Issue by ghost** [EPNW/painter#12] opened 2019-04-27 09:11 UTC

**Comment by ghost** [comment] 2019-04-27 10:24
```
Compiler message:                                                       
file:///home/chandra/flutter/.pub-cache/hosted/pub.dartlang.org/painter-0.3.1/lib/painter.dart:167:20: Error: A value of type 'Future<Image>' can't be assigned to a variable of type 
'Image'.
 - 'Future' is from 'dart:async'.                                       
 - 'Image' is from 'dart:ui'.                                           
Try changing the type of the left hand side, or casting the right hand side to 'Image'.
    return picture.toImage(width, height);                              
                   ^                                                    
Compiler failed on /home/chandra/Projects/aircheq/aircheq/lib/main.dart 
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         5.5s
Gradle task assembleDebug failed with exit code 1
```

**Comment by EP-u-NW** [comment] 2020-04-20 05:59
Duplicate of #8.

**Closed as completed by EP-u-NW** 2020-04-20 05:59 UTC
Labels: duplicate
